// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqimokuuebkwhhyzlkvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxaW1va3V1ZWJrd2hoeXpsa3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MTY3NTQsImV4cCI6MjA3NDA5Mjc1NH0.M6MO0mPteQFCx4-G3REOjHzcqZ_NfIss2yPEgWcIB6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});